solver: 'solvers\quicksort_center.exe'
n: 50
iteration: 100000
restart: 20000
seed: 4321
dirname: 'results\quicksort_c_4321_50'
gpu: 0
form: 1

opt: 'Adam'

p: 0.1

eps: 0.01

lr: 0.0001
noreplay: False