solver: 'C:\Users\sudo__7lummo7\Desktop\HiSampler\HiSampler-master\solvers\quicksort_left.exe'
n: 30
iteration: 100000
restart: 10000
seed: 1234
dirname: 'C:\Users\sudo__7lummo7\Desktop\HiSampler\HiSampler-master\results\quicksort_l'
gpu: 0
form: 1

opt: 'Adam'

p: 0.1

eps: 0.01

lr: 0.00001
noreplay: True