solver: 'solvers\shortest_path.exe'
n:  16
iteration: 100000
restart: 10000
seed: 1234
dirname: 'results\shortest_path_DQN_n16_tensorflow_rainbow_noisy'
gpu: 0
form: 2

opt: 'Adam'

p: 0.1

eps: 0.01

lr: 0.0001
noreplay: False

# 下記不要
epoch: 100000
erp: 0.8
message: 500
step: 100