solver: 'C:\Users\sudo__7lummo7\Desktop\HiSampler\HiSampler-master\solvers\shortest_path.exe'
n: 10
iteration: 100000
restart: 10000
seed: 1234
dirname: 'C:\Users\sudo__7lummo7\Desktop\HiSampler\HiSampler-master\results\shortest_path'
gpu: 0
form: 2

opt: 'Adam'

p: 0.1

eps: 0.01

lr: 0.0001
noreplay: False

epoch: 10000
erp: 0.8
message: 10